<?php
/**
 * Database - single shared PDO connection.
 * Module : Shared core - EcoCampus Waste Management System
 * Every query in the system goes through this class, and every query is
 * a PREPARED STATEMENT. Values are sent to MySQL separately from the SQL
 * text, so user input can never be parsed as SQL. This is the system-wide
 * defense against SQL Injection.
 * Note: this class uses a single shared instance (Singleton). Per the
 * assignment brief, Singleton does NOT count as your reportable design
 * pattern - it is infrastructure, not the pattern you write about.
 */
class Database
{
    private static ?Database $instance = null;
    private PDO $pdo;

    private function __construct()
    {
        $dsn = 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=' . DB_CHARSET;

        $options = [
            // Throw exceptions instead of failing silently.
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            // Return plain associative arrays; our models turn them into objects.
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            // Use REAL prepared statements, not PDO's client-side emulation.
            PDO::ATTR_EMULATE_PREPARES   => false,
        ];

        try {
            $this->pdo = new PDO($dsn, DB_USER, DB_PASS, $options);
        } catch (PDOException $e) {
            // Never show connection details (host, user) to the browser.
            if (DEBUG) {
                die('Database connection failed: ' . $e->getMessage());
            }
            die('The system is temporarily unavailable. Please try again later.');
        }
    }

    /** Returns the one shared Database instance, creating it on first use. */
    public static function getInstance(): Database
    {
        if (self::$instance === null) {
            self::$instance = new Database();
        }
        return self::$instance;
    }

    /** The underlying PDO handle, for code that needs it directly. */
    public function pdo(): PDO
    {
        return $this->pdo;
    }

    /**
     * Runs a prepared statement and returns the PDOStatement.
     *
     * @param string $sql    SQL with ? or :named placeholders - NEVER concatenate user input
     * @param array  $params values to bind to those placeholders
     */
    public function query(string $sql, array $params = []): PDOStatement
    {
        $statement = $this->pdo->prepare($sql);
        $statement->execute($params);
        return $statement;
    }

    /** Returns every matching row as an associative array. */
    public function selectAll(string $sql, array $params = []): array
    {
        return $this->query($sql, $params)->fetchAll();
    }

    /** Returns the first matching row, or null when nothing matched. */
    public function selectOne(string $sql, array $params = []): ?array
    {
        $row = $this->query($sql, $params)->fetch();
        return $row === false ? null : $row;
    }

    /** The AUTO_INCREMENT id generated by the last INSERT. */
    public function lastInsertId(): int
    {
        return (int) $this->pdo->lastInsertId();
    }

    // Prevent cloning or unserialising a second connection into existence.
    private function __clone() {}
    public function __wakeup()
    {
        throw new Exception('Cannot unserialize a singleton.');
    }
}
